apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- deployment.yaml
- service.yaml

images:
- name: my-app-image # <-- The image name *as it appears* in your base deployment.yaml
  newName: 123456789012.dkr.ecr.us-east-1.amazonaws.com/my-app-repo
  newTag: placeholder # <-- This tag will be replaced by the GitHub Action